name: Deploy App
on:
    push:
        branches:
            - main
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Action Checkout
              uses: actions/checkout@v3
            - name: Node Js Setup
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build